name: Create GitHub Token

on:
  push:
    branches: [ main ]

jobs:
  create-token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create GitHub App Token
        id: create-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Use the token
        env:
          GITHUB_TOKEN: ${{ steps.create-token.outputs.token }}
        run: |
          echo "NEXT_PUBLIC_GITHUB_TOKEN=$GITHUB_TOKEN" >> $GITHUB_ENV

      - name: Update .env file
        run: |
          echo "NEXT_PUBLIC_GITHUB_TOKEN=${{ env.NEXT_PUBLIC_GITHUB_TOKEN }}" > .env.local

